Assignment 8 rest
rukshonarad/html pull request #16
Opened 2023-04-28 13:08 UTC by rukshonarad

2023-04-28 19:54 UTC, kulievtech commented on assignment/assignment-8-timed/assignment-8.6.html
> +                name="name"
fullName is better choice for name attribute.

2023-04-28 19:54 UTC, kulievtech commented on assignment/assignment-8-timed/assignment-8.6.html
> +                name="attendance"
attendanceStatus would be better for name attribute.

2023-04-28 19:54 UTC, kulievtech commented on assignment/assignment-8-timed/assignment-8.6.html
> +                name="guests"
numberOfGuests is better choice for name attribute.

2023-04-28 19:54 UTC, kulievtech commented on assignment/assignment-8-timed/assignment-8.6.html
> +            <label for="mealSellect">Meal Preference:</label>
typo: Should be "Select" only 1 L.

2023-04-28 19:54 UTC, kulievtech commented on assignment/assignment-8-timed/assignment-8.6.html
> +            <textarea id="notes" id="notesTextarea" name="notes"></textarea
additonalNotes is better choice for name attribute.

2023-04-28 20:43 UTC, hulkarsharif commented on assignment/assignment-8-timed/assignment-8.2.html
> +                id="confidence"
for and id should be match

2023-04-28 20:44 UTC, hulkarsharif commented on assignment/assignment-8-timed/assignment-8.2.html
> +                name="confidenceRangeInput"
I guess you change the name into id

2023-04-28 20:47 UTC, hulkarsharif commented on assignment/assignment-8-timed/assignment-8.2.html
> +                name="categories"
I would say favoriteHistoryInput

2023-04-28 20:50 UTC, hulkarsharif commented on assignment/assignment-8-timed/assignmeny-8.4.html
> +            <label for="ameInput">Name:</label>
typo missed n

2023-04-28 20:52 UTC, hulkarsharif commented on assignment/assignment-8-timed/assignmeny-8.4.html
> +            <label for="contactMethodSellect">Preferred Contact Method:</label>
typo on sellect must be select

2023-04-28 20:52 UTC, hulkarsharif commented on assignment/assignment-8-timed/assignmeny-8.4.html
> +            <textarea id="feedbackTexarea" name="feedback"></textarea
typo missed t on testarea

2023-04-28 20:54 UTC, hulkarsharif commented on assignment/assignment-8-timed/assignment-8.5.html
> +            <select id="categorySellect" name="category" required>
typo select

2023-04-28 20:55 UTC, hulkarsharif commented on assignment/assignment-8-timed/assignment-8.5.html
> +                name="additional-info"
I am not sure but must be without -

2023-04-28 22:52 UTC, rukshonarad commented on assignment/assignment-8-timed/assignment-8.6.html
> +                name="name"
Ok. I'll fix

2023-04-28 22:53 UTC, rukshonarad commented on assignment/assignment-8-timed/assignment-8.2.html
> +                name="confidenceRangeInput"
yes my bad

2023-04-28 23:14 UTC, rukshonarad commented on assignment/assignment-8-timed/assignmeny-8.4.html
> +            <textarea id="feedbackTexarea" name="feedback"></textarea
good catch

2023-04-28 23:39 UTC, rukshonarad commented on assignment/assignment-8-timed/assignment-8.5.html
> +            <select id="categorySellect" name="category" required>
again same typo ) thanks

2023-04-28 23:40 UTC, rukshonarad commented on assignment/assignment-8-timed/assignment-8.6.html
> +                name="guests"
I'll change tx

2023-04-29 01:16 UTC, PokizaSdv commented on assignment/assignment-8-timed/assignment-8.2.html
> +                name="format"
name should be more specific. for ex. quizFormat or preferredQuizFormat

2023-04-29 01:22 UTC, rukshonarad commented on assignment/assignment-8-timed/assignment-8.2.html
> +                name="format"
I’m on it

2023-04-29 03:51 UTC, durdonadev commented on assignment/assignment-8-timed/assignment-8.7.html
> +                name="name"
"fullName" is better choice for name attr

2023-04-29 03:52 UTC, durdonadev commented on assignment/assignment-8-timed/assignment-8.7.html
> +
It is better to use div instead of br in this case. Like:
"div" label input "/div"

2023-04-29 03:54 UTC, durdonadev commented on assignment/assignment-8-timed/assignment-8.7.html
> +            <label for="termsInput"
Better choice for attr for,id="agreementCheckboxInput"
name="agreement"

2023-04-29 03:54 UTC, durdonadev commented on assignment/assignment-8-timed/assignment-8.7.html
> +            <label for="countrySellect">Country:</label>
typo: "countrySelect"

2023-04-29 21:40 UTC, asilbektech approved these changes

2023-04-30 03:21 UTC, durdonadev commented on assignment/assignment-8-timed/assignment-8.7.html
> +                    id="agreementCheckboxInput"
Now it looks great! 
But also you can drop "Input" in checkbox and radio input types for id,for attr. Like: id="agreementCheckbox"

2023-04-30 19:13 UTC, PokizaSdv commented on assignment/assignment-8-timed/assignment-8.2.html
> +            <input type="checkbox" id="historyCheckboxinput" name="history" />
would be better if you use historyCategoryCheckbox for id and for attr
and isHistoryChecked for name

2023-04-30 19:14 UTC, PokizaSdv commented on assignment/assignment-8-timed/assignment-8.2.html
> +            <label for="scienceCheckboxInput">Science</label><br />
same with history

2023-04-30 19:15 UTC, PokizaSdv commented on assignment/assignment-8-timed/assignment-8.2.html
> +                name="literature"
same

2023-04-30 19:16 UTC, PokizaSdv commented on assignment/assignment-8-timed/assignment-8.2.html
>              <label for="timezone">Time Zone:</label>
timezoneSelect better for id and for

2023-04-30 19:17 UTC, PokizaSdv commented on assignment/assignment-8-timed/assignment-8.2.html
> +            ><br />
to give a break better idea is using div tag not br

2023-04-30 20:38 UTC, durdonadev approved these changes

2023-05-01 01:39 UTC, ohunazz requested changes

2023-05-01 01:39 UTC, ohunazz commented on assignment/assignment-8-timed/assignment-8.1.html
> +                <input type="checkbox" id="sportCheckboxInput" name="sports" />
You can add "value" attr

2023-05-01 09:03 UTC, asilbektech approved these changes

2023-05-01 14:35 UTC, hulkarsharif approved these changes

2023-05-02 04:02 UTC, PokizaSdv approved these changes

2023-05-02 11:58 UTC, kulievtech approved these changes

2023-05-02 18:08 UTC, ohunazz approved these changes

2023-05-03 22:01 UTC, merged